### PR TITLE
Fixed sort returns

### PR DESCRIPTION
**Pull request by YerBoySisi**
I fixed what you said to fix and made it return the original array instead of the changed array

### CODE REVIEW

**Comment by YerBoySisi** [comment]
Hey Mr. Nockles, this is Sisiame.

Out of curiosity, did my sorts end up working as intended? I actually want
to fix them if they're still wrong.

**Comment by bnockles** [comment]
No. I pulled your code, but it performed no better.

**Comment by YerBoySisi** [comment]
Do you know what the exact error with it was? I tested it at home and in
class with a bunch of inputs, and they all worked well. I think there must
be just one value off in each sort.

**Comment by bnockles** [comment]
Sisiame, what am I going to do with you? We should sit down for another talk or something.

Listen, you have a lot of talent and a great attitude. You are a leader among your peers You’ve got a lot going for you. Your only problem is you don’t prioritize attendance and now you want to have discussions about assignments after the due date and semester deadline. For the sake of your learning, I really want to have this conversation with you and help you get to the bottom of what went wrong, but before we have that conversation I need you to know that this sort of thing is not okay. During Regents week, I have other responsibilities and while I understand that it is frustrating for you to have submitted twice but not fixed the error, the responsibility of submitting a program that works is yours.

I will try to look at your code later today and get back to you when I can with more feedback.

-Mr. Nockles

**Comment by YerBoySisi** [comment]
Alright, thank you for looking into it. I created a different pull request
where I changed all the tasks to use only insertion sort, for the sake of
the grade as opposed to efficiency.

**Pull request merged**
